fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/Adaptavist/puppet-stdlib"
    puppi:
      repo: "https://github.com/Adaptavist/puppet-puppi"
    apt:
      repo: "https://github.com/Adaptavist/puppet-apt"
      ref: '1.8.0'
    yum:
      repo: "https://github.com/Adaptavist/puppet-yum"
  symlinks:
    packages_repos: "#{source_dir}"
